steps:
  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}',
      '--build-arg', 'NEXT_PUBLIC_API_URL=${_API_URL}',
      '-t', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '.'
    ]

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '--platform', '${_PLATFORM}',
      '--region', '${_DEPLOY_REGION}',
      '--allow-unauthenticated',
      '--port', '3000',
      '--set-env-vars', 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}',
      '--set-env-vars', 'API_URL=${_API_URL}',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10'
    ] 