steps:
  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: [
      'build',
      '-t', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '.'
    ]

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '--platform', '${_PLATFORM}',
      '--region', '${_DEPLOY_REGION}',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '2Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--set-env-vars', 'DEBUG_MODE=${_DEBUG_MODE}',
      '--set-env-vars', 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}',
      '--set-env-vars', 'DB_USER=${_DB_USER}',
      '--set-env-vars', 'DB_NAME=${_DB_NAME}',
      '--set-env-vars', 'GOOGLE_APPLICATION_CREDENTIALS=/app/intellibook-credentials.json',
      '--set-env-vars', 'ALLOWED_EMAIL=${_ALLOWED_EMAIL}',
      '--set-env-vars', 'FRONTEND_URL=${_FRONTEND_URL}',
      '--set-secrets', 'GOOGLE_API_KEY=google-api-key:latest',
      '--set-secrets', 'DB_PASS=db-pass:latest',
      '--set-secrets', 'GOOGLE_CLIENT_ID=google-client-id:latest',
      '--set-secrets', 'GOOGLE_APPLICATION_CREDENTIALS_JSON=google-application-credentials:latest'
    ]

# Logging configuration
options:
  logging: CLOUD_LOGGING_ONLY 